### ISSUE TITLE
ListResponse more method needs review

### ISSUE THREAD

**Issue by brianneking86** [giantmachines/square-ruby#1]
calling more on an instance of a ListResponse returns an array not a ListResponse. I have made an adjustment that gives the correct return value but it needs review. I think there has to be a better way to do it.

**Comment by dmichael** [comment]
Yes :) - at the moment the ListResponse is a child of Array. A more idomatic way of dealing with it would be to mixin Enumerable to ListResponse.

**Comment by brianmcallister** [comment]
Done.
